name: CI Pipeline
run-name: Pruebas de Integración Continua por @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Test on ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Pruebas solo para las versiones de Ubuntu 24.04 y 22.04
        os: [ubuntu-24.04, ubuntu-22.04]
        # Pruebas para las versiones de python 3.8 y 3.12
        python-version: ["3.8", "3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verificar el formato del texto
      run: ruff check .

    - name: Ejecutar las pruebas (tests)
      run: pytest